server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /olxadvertise-monitor
  health:    circuitbreakers:      enabled: true
  endpoint:    health:
      enabled: true      show-details: always
      
spring:
  config:
    import: configserver:http://localhost:8888  
  application:
    name: olx-advertise
  zipkin:    base-url: http://localhost:9411
eureka:  instance:    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://${eureka.instance.hostname}:8761/eureka


resilience4j:
  circuitbreaker:
    instances:
      AUTH_TOKEN_VALIDATION:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      CATEGORY:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      STATUS:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s

